### ISSUE TITLE
Error loading elasticsearch

### ISSUE THREAD

**Issue by MrBoggi** [legrego/homeassistant-elasticsearch#23] opened 2018-09-01 06:30 UTC
HA Version: 0.77
ELK version: 6.3.2

I just added this to my home assistant. Copied files as described and configured my configuration.yaml to point to my server running the ELK stack. After restarting HA I get the following error:

`
2018-09-01 08:11:53 ERROR (MainThread) [homeassistant.setup] Error during setup of component elastic
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/setup.py", line 145, in _async_setup_component
    hass, processed_config)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 212, in coro
    res = func(*args, **kw)
  File "/config/custom_components/elastic.py", line 62, in async_setup
    gateway = ElasticsearchGateway(hass, conf)
  File "/config/custom_components/elastic.py", line 126, in __init__
    self.client = self._create_es_client()
  File "/config/custom_components/elastic.py", line 134, in _create_es_client
    import elasticsearch
ModuleNotFoundError: No module named 'elasticsearch'
`

My config in HA is as follows:
elastic:
    # URL should point to your Elasticsearch cluster
    url: http://192.168.1.10:9200

And if I browse the url I get the default elasticsearch response:
`{
  "name" : "oTddzKZ",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "mmt9dUJxQFunPQUve-kdcg",
  "version" : {
    "number" : "6.3.2",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "053779d",
    "build_date" : "2018-07-20T05:20:23.451332Z",
    "build_snapshot" : false,
    "lucene_version" : "7.3.1",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}`

any ideas as to what is wrong here? I guess it tries to find a library named elasticsearch on my HA computer but it has no ELK installation.

**Comment by legrego** [comment] 2018-09-01 19:58
I agree with you -- based on the error message, it looks like HA failed to download the `elasticsearch` client dependency. I'm on HA `0.74` right now, but let me test on a fresh install of `0.77` to see if I can reproduce.

Sorry to ask the obvious, but have you tried restarting HA to see if that fixes the problem?

Otherwise, are you able to check if the `elasticsearch` package is installed by HA? (see https://developers.home-assistant.io/docs/en/creating_component_deps_and_reqs.html#requirements)

**Comment by MrBoggi** [comment] 2018-09-02 05:39
Hi

I was pretty shure I restarted but.. Well.. did a new restart now and I cannot find the error in the HA log and it seems like I get data into my ELK :) So.. A classic example of PEBKAC (Problem exists between keyboard and chair)

**Comment by MrBoggi** [comment] 2018-09-02 06:05
I think we just saw a typical example of PEBKAC here. So now it loads as it should but I see the following error now:

2018-09-02 07:48:00 ERROR (MainThread) [custom_components.elastic] Error publishing documents to Elasticsearch: ({'domain': 'zwave', 'entity_id': 'e2_kontor_varme_gulvtermostat', 'attributes': {'node_id': 19, 'node_name': 'Kontor Gulvvarme', 'manufacturer_name': 'ThermoFloor AS', 'product_name': 'Heatit Thermostat TF 021', 'query_stage': 'Complete', 'is_awake': True, 'is_ready': True, 'is_failed': False, 'is_info_received': True, 'max_baud_rate': 40000, 'is_zwave_plus': True, 'capabilities': {'listening', 'zwave_plus', 'beaming', 'routing'}, 'neighbors': {128, 1, 8, 9, 10, 13, 21, 24, 27, 28, 29, 36, 38, 73, 84, 111, 118, 119, 120, 121, 122, 125}, 'sentCnt': 12, 'sentFailed': 0, 'retries': 0, 'receivedCnt': 29, 'receivedDups': 2, 'receivedUnsolicited': 22, 'sentTS': '2018-09-02 07:32:26:942 ', 'receivedTS': '2018-09-02 07:47:02:627 ', 'lastRequestRTT': 119, 'averageRequestRTT': 80, 'lastResponseRTT': 134, 'averageResponseRTT': 100, 'friendly_name': 'Kontor Gulvvarme'}, 'time': datetime.datetime(2018, 9, 2, 5, 47, 2, 739831, tzinfo=<UTC>), 'value': 'ready'}, TypeError("Unable to serialize {'listening', 'zwave_plus', 'beaming', 'routing'} (type: <class 'set'>)",))


Traceback (most recent call last):


  File "/config/deps/lib/python3.6/site-packages/elasticsearch/serializer.py", line 52, in dumps


    separators=(',', ':'),


  File "/usr/local/lib/python3.6/site-packages/simplejson/__init__.py", line 399, in dumps


    **kw).encode(obj)


  File "/usr/local/lib/python3.6/site-packages/simplejson/encoder.py", line 296, in encode


    chunks = self.iterencode(o, _one_shot=True)


  File "/usr/local/lib/python3.6/site-packages/simplejson/encoder.py", line 378, in iterencode


    return _iterencode(o, 0)


  File "/config/deps/lib/python3.6/site-packages/elasticsearch/serializer.py", line 34, in default


    raise TypeError("Unable to serialize %r (type: %s)" % (data, type(data)))


TypeError: Unable to serialize {'listening', 'zwave_plus', 'beaming', 'routing'} (type: <class 'set'>)




During handling of the above exception, another exception occurred:




Traceback (most recent call last):


  File "/config/custom_components/elastic.py", line 205, in do_publish


    bulk_response = bulk(self._gateway.get_client(), actions)


  File "/config/deps/lib/python3.6/site-packages/elasticsearch/helpers/__init__.py", line 257, in bulk


    for ok, item in streaming_bulk(client, actions, *args, **kwargs):


  File "/config/deps/lib/python3.6/site-packages/elasticsearch/helpers/__init__.py", line 180, in streaming_bulk


    client.transport.serializer):


  File "/config/deps/lib/python3.6/site-packages/elasticsearch/helpers/__init__.py", line 64, in _chunk_actions


    data = serializer.dumps(data)


  File "/config/deps/lib/python3.6/site-packages/elasticsearch/serializer.py", line 55, in dumps


    raise SerializationError(data, e)


elasticsearch.exceptions.SerializationError: ({'domain': 'zwave', 'entity_id': 'e2_kontor_varme_gulvtermostat', 'attributes': {'node_id': 19, 'node_name': 'Kontor Gulvvarme', 'manufacturer_name': 'ThermoFloor AS', 'product_name': 'Heatit Thermostat TF 021', 'query_stage': 'Complete', 'is_awake': True, 'is_ready': True, 'is_failed': False, 'is_info_received': True, 'max_baud_rate': 40000, 'is_zwave_plus': True, 'capabilities': {'listening', 'zwave_plus', 'beaming', 'routing'}, 'neighbors': {128, 1, 8, 9, 10, 13, 21, 24, 27, 28, 29, 36, 38, 73, 84, 111, 118, 119, 120, 121, 122, 125}, 'sentCnt': 12, 'sentFailed': 0, 'retries': 0, 'receivedCnt': 29, 'receivedDups': 2, 'receivedUnsolicited': 22, 'sentTS': '2018-09-02 07:32:26:942 ', 'receivedTS': '2018-09-02 07:47:02:627 ', 'lastRequestRTT': 119, 'averageRequestRTT': 80, 'lastResponseRTT': 134, 'averageResponseRTT': 100, 'friendly_name': 'Kontor Gulvvarme'}, 'time': datetime.datetime(2018, 9, 2, 5, 47, 2, 739831, tzinfo=<UTC>), 'value': 'ready'}, TypeError("Unable to serialize {'listening', 'zwave_plus', 'beaming', 'routing'} (type: <class 'set'>)",))

Does it create indexes itself or?

**Comment by legrego** [comment] 2018-09-02 12:37
Thanks for the followup @MrBoggi!

It looks like you've found a bug -- I am not serializing python `sets` correctly. I've opened https://github.com/legrego/homeassistant-elasticsearch/issues/26 to track this.

**Comment by legrego** [comment] 2018-09-02 19:55
Closing as the original issue was resolved 👍

**Closed by legrego** 2018-09-02 19:55 UTC
