### ISSUE TITLE
failed to parse field [hass.attributes.visibility] of type [long]

### ISSUE THREAD

**Issue by kkellner** [legrego/homeassistant-elasticsearch#91] opened 2020-03-27 08:06 UTC
I installed `browser_mod` from community store.   After installing it, I'm getting the following error in HA log.  I've tried deleting ES index hoping that when it was recreated it might fix the issue but same problem.   Ideas on how to fix?

`
2020-03-27 01:51:37 ERROR (MainThread) [custom_components.elastic] Error publishing documents to Elasticsearch: ('1 document(s) failed to index.', [{'index': {'_index': 'hass-events-v4-000001', '_type': 'doc', '_id': 'nyf5GnEB1v_E5Tv-lzqf', 'status': 400, 'error': {'type': 'mapper_parsing_exception', 'reason': "failed to parse field [hass.attributes.visibility] of type [long] in document with id 'nyf5GnEB1v_E5Tv-lzqf'", 'caused_by': {'type': 'illegal_argument_exception', 'reason': 'For input string: "visible"'}}, 'data': {'hass.domain': 'sensor', 'hass.object_id': 'browser_mod_macos_kurt', 'hass.object_id_lower': 'browser_mod_macos_kurt', 'hass.entity_id': 'sensor.browser_mod_macos_kurt', 'hass.entity_id_lower': 'sensor.browser_mod_macos_kurt', 'hass.attributes': {'type': 'browser_mod', 'last_seen': datetime.datetime(2020, 3, 27, 1, 51, 35, 475065), 'deviceID': 'b5b73691-86c87b33', 'path': '/config/server_control', 'visibility': 'visible', 'userAgent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36', 'currentUser': 'auser', 'width': 1920, 'height': 1121}, 'hass.value': 2.0, '@timestamp': datetime.datetime(2020, 3, 27, 7, 51, 35, 475388, tzinfo=<UTC>), 'agent.name': 'My Home Assistant', 'agent.type': 'hass', 'agent.version': '0.107.7', 'ecs.version': '1.0.0', 'host.geo.location': {'lat': 999, 'lon': -999}, 'host.architecture': 'x86_64', 'host.os.name': 'Linux', 'host.hostname': 'homeassistant', 'tags': ['hass']}}}])
`

```python
Traceback (most recent call last):
  File "/config/custom_components/elastic/__init__.py", line 519, in do_publish
    bulk_response = bulk(self._gateway.get_client(), actions)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/helpers/__init__.py", line 257, in bulk
    for ok, item in streaming_bulk(client, actions, *args, **kwargs):
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/helpers/__init__.py", line 192, in streaming_bulk
    raise_on_error, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/helpers/__init__.py", line 137, in _process_bulk_chunk
    raise BulkIndexError('%i document(s) failed to index.' % len(errors), errors)
```

`
elasticsearch.helpers.BulkIndexError: ('1 document(s) failed to index.', [{'index': {'_index': 'hass-events-v4-000001', '_type': 'doc', '_id': 'nyf5GnEB1v_E5Tv-lzqf', 'status': 400, 'error': {'type': 'mapper_parsing_exception', 'reason': "failed to parse field [hass.attributes.visibility] of type [long] in document with id 'nyf5GnEB1v_E5Tv-lzqf'", 'caused_by': {'type': 'illegal_argument_exception', 'reason': 'For input string: "visible"'}}, 'data': {'hass.domain': 'sensor', 'hass.object_id': 'browser_mod_macos_kurt', 'hass.object_id_lower': 'browser_mod_macos_kurt', 'hass.entity_id': 'sensor.browser_mod_macos_kurt', 'hass.entity_id_lower': 'sensor.browser_mod_macos_kurt', 'hass.attributes': {'type': 'browser_mod', 'last_seen': datetime.datetime(2020, 3, 27, 1, 51, 35, 475065), 'deviceID': 'b5b73691-86c87b33', 'path': '/config/server_control', 'visibility': 'visible', 'userAgent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36', 'currentUser': 'auser', 'width': 1920, 'height': 1121}, 'hass.value': 2.0, '@timestamp': datetime.datetime(2020, 3, 27, 7, 51, 35, 475388, tzinfo=<UTC>), 'agent.name': 'My Home Assistant', 'agent.type': 'hass', 'agent.version': '0.107.7', 'ecs.version': '1.0.0', 'host.geo.location': {'lat': 999, 'lon': -999}, 'host.architecture': 'x86_64', 'host.os.name': 'Linux', 'host.hostname': 'homeassistant', 'tags': ['hass']}}}])
`

**Comment by untergeek** [comment] 2020-04-01 15:50
@legrego This is going to explode as a problem. I can confirm this happens with my setup with a fresh pull from GitHub this morning.

The first document that goes through Elasticsearch will set the mapping.

The first `hass.attributes.value` that went through for mine had a `float`:
```
                "value" : {
                  "type" : "float"
                },
```

So everything that comes later that is string-based will fail:

```
elasticsearch.helpers.BulkIndexError: ('27 document(s) failed to index.', [{'index': {'_index': 'hass-events-v4-000001', '_type': '_doc', '_id': 'PlxiNnEBwRRG37EuHzrL', 'status': 400, 'error': {'type': 'mapper_parsing_exception', 'reason': "failed to parse field [hass.attributes.value] of type [float] in document with id 'PlxiNnEBwRRG37EuHzrL'. Preview of field's value: 'Clear'", 'caused_by': {'type': 'number_format_exception', 'reason': 'For input string: "Clear"'}}, 'data': {'hass.domain': 'sensor', 'hass.object_id': 'garage_4in1_multisensor_alarm_home_security', 'hass.object_id_lower': 'garage_4in1_multisensor_alarm_home_security', 'hass.entity_id': 'sensor.garage_4in1_multisensor_alarm_home_security', 'hass.entity_id_lower': 'sensor.garage_4in1_multisensor_alarm_home_security', 'hass.attributes': {'time': 1585754025620, 'value': 'Clear', 'friendly_name': 'Garage 4in1 Alarm Home Security', 'icon': 'mdi:alarm-light'}, 'hass.value': 'Clear', '@timestamp': datetime.datetime(2020, 4, 1, 15, 35, 32, 223027, tzinfo=<UTC>), 'agent.name': 'My Home Assistant', 'agent.type': 'hass', 'agent.version': '0.107.4', 'ecs.version': '1.0.0', 'host.geo.location': {'lat': 40.038433314542345, 'lon': -111.65652036666872}, 'host.architecture': 'x86_64', 'host.os.name': 'Linux', 'host.hostname': 'odroidh2-08', 'tags': ['hass']}}},
```
Pointedly, the JSON has `{"value": "Clear"}` in it. This cannot map.

I'm not sure how best to address this.

Ideas include forcing `hass.attributes.value` into an _object_, and have subfields text, keyword, int(long), and float(double?) and attempt to transparently cast values into these types, silently ignoring failures.

This would allow numeric data or textual data without dramatically altering the mapping.

Thoughts?

**Comment by untergeek** [comment] 2020-04-01 20:05
@kkellner I have a workaround for you. I worked with @legrego on this, and it may become the new template.

```
{
  "order": 0,
  "index_patterns": [
    "hass-events-v4*"
  ],
  "settings": {
    "index": {
      "lifecycle": {
        "name": "home-assistant",
        "rollover_alias": "active-hass-index-v4"
      },
      "number_of_shards": "1",
      "codec": "best_compression",
      "mapping": {
        "total_fields": {
          "limit": "10000"
        }
      }
    }
  },
  "mappings": {
    "dynamic": "strict",
    "dynamic_templates": [
      {
        "hass_attributes": {
          "path_match": "hass.attributes.*",
          "mapping": {
            "type": "text",
            "fields": {
              "keyword": {
                "ignore_above": 128,
                "type": "keyword"
              },
              "float": {
                "ignore_malformed": true,
                "type": "float"
              }
            }
          }
        }
      }
    ],
    "properties": {
      "agent": {
        "properties": {
          "name": {
            "ignore_above": 128,
            "type": "keyword"
          },
          "id": {
            "ignore_above": 128,
            "type": "keyword"
          },
          "ephemeral_id": {
            "ignore_above": 128,
            "type": "keyword"
          },
          "type": {
            "ignore_above": 128,
            "type": "keyword"
          },
          "version": {
            "ignore_above": 128,
            "type": "keyword"
          }
        }
      },
      "@timestamp": {
        "type": "date"
      },
      "ecs": {
        "properties": {
          "version": {
            "ignore_above": 128,
            "type": "keyword"
          }
        }
      },
      "host": {
        "properties": {
          "geo": {
            "properties": {
              "continent_name": {
                "ignore_above": 128,
                "type": "keyword"
              },
              "region_iso_code": {
                "ignore_above": 128,
                "type": "keyword"
              },
              "city_name": {
                "ignore_above": 128,
                "type": "keyword"
              },
              "country_iso_code": {
                "ignore_above": 128,
                "type": "keyword"
              },
              "country_name": {
                "ignore_above": 128,
                "type": "keyword"
              },
              "name": {
                "ignore_above": 128,
                "type": "keyword"
              },
              "location": {
                "type": "geo_point"
              },
              "region_name": {
                "ignore_above": 128,
                "type": "keyword"
              }
            }
          },
          "hostname": {
            "ignore_above": 128,
            "type": "keyword"
          },
          "os": {
            "properties": {
              "kernel": {
                "ignore_above": 128,
                "type": "keyword"
              },
              "name": {
                "ignore_above": 128,
                "type": "keyword"
              },
              "family": {
                "ignore_above": 128,
                "type": "keyword"
              },
              "version": {
                "ignore_above": 128,
                "type": "keyword"
              },
              "platform": {
                "ignore_above": 128,
                "type": "keyword"
              },
              "full": {
                "ignore_above": 128,
                "type": "keyword"
              }
            }
          },
          "ip": {
            "type": "ip"
          },
          "name": {
            "ignore_above": 128,
            "type": "keyword"
          },
          "id": {
            "ignore_above": 128,
            "type": "keyword"
          },
          "type": {
            "ignore_above": 128,
            "type": "keyword"
          },
          "user": {
            "properties": {
              "full_name": {
                "ignore_above": 128,
                "type": "keyword"
              },
              "name": {
                "ignore_above": 128,
                "type": "keyword"
              },
              "id": {
                "ignore_above": 128,
                "type": "keyword"
              },
              "email": {
                "ignore_above": 128,
                "type": "keyword"
              },
              "hash": {
                "ignore_above": 128,
                "type": "keyword"
              }
            }
          },
          "mac": {
            "ignore_above": 128,
            "type": "keyword"
          },
          "architecture": {
            "ignore_above": 128,
            "type": "keyword"
          }
        }
      },
      "hass": {
        "type": "object",
        "properties": {
          "geo": {
            "type": "object",
            "properties": {
              "location": {
                "type": "geo_point"
              }
            }
          },
          "object_id_lower": {
            "ignore_above": 124,
            "type": "keyword"
          },
          "domain": {
            "ignore_above": 124,
            "type": "keyword"
          },
          "entity_id_lower": {
            "ignore_above": 124,
            "type": "keyword"
          },
          "attributes": {
            "dynamic": true,
            "type": "object"
          },
          "entity_id": {
            "ignore_above": 124,
            "type": "keyword"
          },
          "object_id": {
            "ignore_above": 124,
            "type": "keyword"
          },
          "value": {
            "type": "text",
            "fields": {
              "keyword": {
                "ignore_above": 2048,
                "type": "keyword"
              },
              "float": {
                "ignore_malformed": true,
                "type": "float"
              }
            }
          }
        }
      },
      "event": {
        "properties": {
          "severity": {
            "type": "long"
          },
          "original": {
            "ignore_above": 128,
            "index": false,
            "type": "keyword",
            "doc_values": false
          },
          "risk_score": {
            "type": "float"
          },
          "created": {
            "type": "date"
          },
          "kind": {
            "ignore_above": 128,
            "type": "keyword"
          },
          "timezone": {
            "ignore_above": 128,
            "type": "keyword"
          },
          "module": {
            "ignore_above": 128,
            "type": "keyword"
          },
          "start": {
            "type": "date"
          },
          "type": {
            "ignore_above": 128,
            "type": "keyword"
          },
          "duration": {
            "type": "long"
          },
          "risk_score_norm": {
            "type": "float"
          },
          "action": {
            "ignore_above": 128,
            "type": "keyword"
          },
          "end": {
            "type": "date"
          },
          "id": {
            "ignore_above": 128,
            "type": "keyword"
          },
          "category": {
            "ignore_above": 128,
            "type": "keyword"
          },
          "dataset": {
            "ignore_above": 128,
            "type": "keyword"
          },
          "hash": {
            "ignore_above": 128,
            "type": "keyword"
          },
          "outcome": {
            "ignore_above": 128,
            "type": "keyword"
          }
        }
      },
      "tags": {
        "ignore_above": 128,
        "type": "keyword"
      }
    }
  },
  "aliases": {
    "all-hass-events": {}
  }
}
```

The primary additions are:

```
      "codec": "best_compression",
      "mapping": {
        "total_fields": {
          "limit": "10000"
        }
      }
```

and

```
    "dynamic_templates": [
      {
        "hass_attributes": {
          "path_match": "hass.attributes.*",
          "mapping": {
            "type": "text",
            "fields": {
              "keyword": {
                "ignore_above": 128,
                "type": "keyword"
              },
              "float": {
                "ignore_malformed": true,
                "type": "float"
              }
            }
          }
        }
      }
    ],
```
A version of this was already in place for `hass.value`, but it is the value collision between similarly named attributes in `hass.attributes` that is causing mapping conflicts like the one you experienced.

In another comment, I will suggest an additional template you can add that will merge these settings but leave the original template alone.

**Comment by untergeek** [comment] 2020-04-01 20:16
Running the following in Dev Tools in Kibana (or if you're clever, using `curl`) will add a template which has a higher `order` value.

If you're not familiar with templating in Elasticsearch, multiple templates can all match the same index via the `index_patterns` array parameter. All such templates are effectively merged at index creation into a single collection of settings and mappings. Templates with a higher `order` will override those with a lower value. This "patch" template has `order: 2`, but these settings would still merge at `order: 0`.

```
PUT _template/hass-index-template-v4_1
{
  "order": 2,
  "index_patterns": [
    "hass-events-v4*"
  ],
  "settings": {
    "index": {
      "codec": "best_compression",
      "mapping": {
        "total_fields": {
          "limit": "1000"
        }
      }
    }
  },
  "mappings": {
    "dynamic": "strict",
    "dynamic_templates": [
      {
        "hass_attributes": {
          "path_match": "hass.attributes.*",
          "mapping": {
            "type": "text",
            "fields": {
              "keyword": {
                "ignore_above": 128,
                "type": "keyword"
              },
              "float": {
                "ignore_malformed": true,
                "type": "float"
              }
            }
          }
        }
      }
    ]
  }
}
```

After adding this template, nothing will happen until a new index is created. Provided you are using the most recent release of `homeassistant-elasticsearch`, and have the ILM settings enabled to use rollover indices, this is as simple as running

```
POST active-hass-index-v4/_rollover
{
  "conditions": {
    "max_age": "1s"
  }
}
```
…in the Dev Tools of Kibana (or in `curl`). This triggers Elasticsearch to roll to a new index if the current one's `creation_date` is more than 1 second ago. The new index will have the new settings, and your documents should map properly without conflict, except in the case of two more gotchas I will address in subsequent comments (to keep things from being too big).

**Comment by untergeek** [comment] 2020-04-01 20:28
# Gotcha 1: Lots and lots of fields

Because of the tremendous variety in attribute naming alone, there will be a high number of fields in your Elasticsearch index. Currently, my index is up to nearly 600 fields. Elasticsearch limits an index to 1,000 fields by default. If you already have 1,000 fields and try to index a new document that has an as-yet unseen field, an error will bounce back indicating such. It will show up in the `home-assistant.log` file and appear somewhat similar to the errors already shared above.

Fortunately this limit is tunable with a setting. To enable the current index to receive more fields, this command will suffice:

```
PUT active-hass-index-v4/_settings
{
  "index": {
    "mapping": {
        "total_fields.limit": 1234
    }
  }
}
```

That addresses the _current_ index only, however. You will need to update the template to also increase the limit for future indices.

In the "patch" mapping above, you'll find I added this default manually, easing an increase, if needed:

```
      "mapping": {
        "total_fields": {
          "limit": "1234"
        }
      }
```

To increase the field count limit, increase the value of `limit` and re-apply the template. All subsequent indices created will have the updated setting.

**Comment by untergeek** [comment] 2020-04-01 21:21
# Gotcha 2: Attribute keys with dots in them

For example, given this sample:
```
  "hass.attributes": {
    "some.user@gmail.com - Roku Ultra": "Movie Title (1900)",
    "unit_of_measurement": "Watching",
    "friendly_name": "Plex (LibraryName)",
    "icon": "mdi:plex"
  },
```
You will see an error like this:
```
      {
        "type" : "class_cast_exception",
        "reason" : "class_cast_exception: class org.elasticsearch.index.mapper.TextFieldMapper cannot be cast to class org.elasticsearch.index.mapper.ObjectMapper (org.elasticsearch.index.mapper.TextFieldMapper and org.elasticsearch.index.mapper.ObjectMapper are in unnamed module of loader 'app')"
      }
```

Elasticsearch tries to expand dots in key names to represent nested fields. Keys like `some.user@gmail.com - Roku Ultra` will therefore break things.

I've just raised this with @legrego directly and will raise a separate issue for it.

In the meanwhile, the only thing you can do is to `exclude` such entities. I've had to exclude `sensor.plex` and that was the only one I've seen so far.

**Comment by kkellner** [comment] 2020-04-02 03:12
Thank you for the deep dive into this issue.   I'm not well versed on elasticsearch....   I tried to run the `hass-index-template-v4_1` in dev tools but got the following response:

```
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "Malformed [mappings] section for type [dynamic], should include an inner object describing the mapping"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "Malformed [mappings] section for type [dynamic], should include an inner object describing the mapping"
  },
  "status": 400
}
```
![image](https://user-images.githubusercontent.com/9540241/78206889-4fee0180-745d-11ea-8352-b49ac99eec9d.png)

**Comment by untergeek** [comment] 2020-04-02 03:31
Which version do you have? It may be you have an older release. I can adapt the template accordingly if I know what you’re using.

**Comment by kkellner** [comment] 2020-04-02 03:37
Elasticsearch version 6.8.3

**Comment by kkellner** [comment] 2020-04-02 15:58
I guess I am behind on my version.   I'll look at upgrading.

**Comment by untergeek** [comment] 2020-04-02 16:36
No need to take it that there yet. We may just need to assign a mapping type of `_doc` to the template for 6.x. Let me do a quick test.

**Comment by untergeek** [comment] 2020-04-02 16:59
You should only need to append `?include_type_name=false` to your request in either the Dev Tools in Kibana, or `curl`. That will make it work.

**Comment by kkellner** [comment] 2020-04-02 18:09
Adding `?include_type_name=false` worked, however it looks like I'm getting a new error from home assistant side.  Not sure if its related as I updated from v6.8.3 to v6.8.8 on elastic search and didn't check the HA logs before I applied `hass-index-template-v4_1`.  However I was getting logs in ES after the v6.8.8 upgrade, but not getting any logs after adding`hass-index-template-v4_1`.

Please note this is not mission critical, so please don't spend much time trying to fix my individual problem.  I'm happy to take a hass elastic plugin update (when the issue is resolved) and delete my current indexes.   However I'm happy to help test if I'm not causing more burden then help.

`
Error publishing documents to Elasticsearch: ('6 document(s) failed to index.', [{'index': {'_index': 'hass-events-v4-000001', '_type': 'doc', '_id': 'IRsKPHEBsScj84T827eV', 'status': 400, 'error': {'type': 'illegal_argument_exception', 'reason': 'Rejecting mapping update to [hass-events-v4-000001] as the final mapping would have more than 1 type: [_doc, doc]'}, 'data': {'hass.domain': 'sensor', 'hass.object_id': 'memory_use_percent', 'hass.object_id_lower': 'memory_use_percent', 'hass.entity_id': 'sensor.memory_use_percent', 'hass.entity_id_lower': 'sensor.memory_use_percent', 'hass.attributes': {'unit_of_measurement': '%', 'friendly_name': 'Memory use (percent)', 'icon': 'mdi:memory'}, 'hass.value': 44.0, '@timestamp': datetime.datetime(2020, 4, 2, 17, 57, 55, 3312, tzinfo=<UTC>), 'agent.name': 'My Home Assistant', 'agent.type': 'hass', 'agent.version': '0.107.7', 'ecs.version': '1.0.0', 'host.geo.location': {'lat': 999, 'lon': -999}, 'host.architecture': 'x86_64', 'host.os.name': 'Linux', 'host.hostname': 'homeassistant', 'tags': ['hass']}}},
...
`

**Comment by untergeek** [comment] 2020-04-02 18:25
Did you completely delete the index and start over? If so, the mapping type complaint would appear to come from differing mapping templates standards between Elasticsearch v6 and v7.

Are you also using the most recent release of `homeassistant-elasticsearch`?

What are the top 25 lines output from: `GET hass-events-v4-000001/_mapping`?

**Comment by kkellner** [comment] 2020-04-02 21:33
This is what I did:
1. stopped home assistant
2. Ran this:
DELETE _template/hass-index-template-v4
DELETE _template/hass-index-template-v4_1
DELETE /hass-events-v4-000001
DELETE /active-hass-index-v4
PUT _template/hass-index-template-v4_1?include_type_name=false  (... with json body)
3. started home assistant

I'm running `homeassistant-elasticsearch` version `v0.2.1`

Output of `GET hass-events-v4-000001/_mapping`:

```
#! Deprecation: [types removal] The parameter include_type_name should be explicitly specified in get mapping requests to prepare for 7.0. In 7.0 include_type_name will default to 'false', which means responses will omit the type name in mapping definitions.
{
  "hass-events-v4-000001" : {
    "mappings" : {
      "_doc" : {
        "dynamic" : "strict",
        "dynamic_templates" : [
          {
            "hass_attributes" : {
              "path_match" : "hass.attributes.*",
              "mapping" : {
                "fields" : {
                  "keyword" : {
                    "ignore_above" : 128,
                    "type" : "keyword"
                  },
                  "float" : {
                    "ignore_malformed" : true,
                    "type" : "float"
                  }
                },
                "type" : "text"
              }
            }
          }
        ],
        "properties" : {
          "@timestamp" : {
            "type" : "date"
          },
          "agent" : {
            "properties" : {
              "ephemeral_id" : {
                "type" : "keyword",
                "ignore_above" : 1024
              },
              "id" : {
                "type" : "keyword",
                "ignore_above" : 1024
              },
              "name" : {
                "type" : "keyword",
                "ignore_above" : 1024
              },
              "type" : {
                "type" : "keyword",
                "ignore_above" : 1024
              },
              "version" : {
                "type" : "keyword",
                "ignore_above" : 1024
              }
            }
          },
          "ecs" : {
            "properties" : {
              "version" : {
                "type" : "keyword",
                "ignore_above" : 1024
              }
            }
          },
          "event" : {
            "properties" : {
              "action" : {
                "type" : "keyword",
                "ignore_above" : 1024
              },
              "category" : {
                "type" : "keyword",
                "ignore_above" : 1024
              },
              "created" : {
                "type" : "date"
              },
              "dataset" : {
                "type" : "keyword",
                "ignore_above" : 1024
              },
              "duration" : {
                "type" : "long"
              },
              "end" : {
                "type" : "date"
              },
              "hash" : {
                "type" : "keyword",
                "ignore_above" : 1024
              },
              "id" : {
                "type" : "keyword",
                "ignore_above" : 1024
              },
              "kind" : {
                "type" : "keyword",
                "ignore_above" : 1024
              },
              "module" : {
                "type" : "keyword",
                "ignore_above" : 1024
              },
              "original" : {
                "type" : "keyword",
                "index" : false,
                "doc_values" : false,
                "ignore_above" : 1024
              },
              "outcome" : {
                "type" : "keyword",
                "ignore_above" : 1024
              },
              "risk_score" : {
                "type" : "float"
              },
              "risk_score_norm" : {
                "type" : "float"
              },
              "severity" : {
                "type" : "long"
              },
              "start" : {
                "type" : "date"
              },
              "timezone" : {
                "type" : "keyword",
                "ignore_above" : 1024
              },
              "type" : {
                "type" : "keyword",
                "ignore_above" : 1024
              }
            }
          },
          "hass" : {
            "properties" : {
              "attributes" : {
                "type" : "object",
                "dynamic" : "true"
              },
              "domain" : {
                "type" : "keyword",
                "ignore_above" : 124
              },
              "entity_id" : {
                "type" : "keyword",
                "ignore_above" : 124
              },
              "entity_id_lower" : {
                "type" : "keyword",
                "ignore_above" : 124
              },
              "geo" : {
                "properties" : {
                  "location" : {
                    "type" : "geo_point"
                  }
                }
              },
              "object_id" : {
                "type" : "keyword",
                "ignore_above" : 124
              },
              "object_id_lower" : {
                "type" : "keyword",
                "ignore_above" : 124
              },
              "value" : {
                "type" : "text",
                "fields" : {
                  "float" : {
                    "type" : "float",
                    "ignore_malformed" : true
                  },
                  "keyword" : {
                    "type" : "keyword",
                    "ignore_above" : 2048
                  }
                }
              }
            }
          },
          "host" : {
            "properties" : {
              "architecture" : {
                "type" : "keyword",
                "ignore_above" : 1024
              },
              "geo" : {
                "properties" : {
                  "city_name" : {
                    "type" : "keyword",
                    "ignore_above" : 1024
                  },
                  "continent_name" : {
                    "type" : "keyword",
                    "ignore_above" : 1024
                  },
                  "country_iso_code" : {
                    "type" : "keyword",
                    "ignore_above" : 1024
                  },
                  "country_name" : {
                    "type" : "keyword",
                    "ignore_above" : 1024
                  },
                  "location" : {
                    "type" : "geo_point"
                  },
                  "name" : {
                    "type" : "keyword",
                    "ignore_above" : 1024
                  },
                  "region_iso_code" : {
                    "type" : "keyword",
                    "ignore_above" : 1024
                  },
                  "region_name" : {
                    "type" : "keyword",
                    "ignore_above" : 1024
                  }
                }
              },
              "hostname" : {
                "type" : "keyword",
                "ignore_above" : 1024
              },
              "id" : {
                "type" : "keyword",
                "ignore_above" : 1024
              },
              "ip" : {
                "type" : "ip"
              },
              "mac" : {
                "type" : "keyword",
                "ignore_above" : 1024
              },
              "name" : {
                "type" : "keyword",
                "ignore_above" : 1024
              },
              "os" : {
                "properties" : {
                  "family" : {
                    "type" : "keyword",
                    "ignore_above" : 1024
                  },
                  "full" : {
                    "type" : "keyword",
                    "ignore_above" : 1024
                  },
                  "kernel" : {
                    "type" : "keyword",
                    "ignore_above" : 1024
                  },
                  "name" : {
                    "type" : "keyword",
                    "ignore_above" : 1024
                  },
                  "platform" : {
                    "type" : "keyword",
                    "ignore_above" : 1024
                  },
                  "version" : {
                    "type" : "keyword",
                    "ignore_above" : 1024
                  }
                }
              },
              "type" : {
                "type" : "keyword",
                "ignore_above" : 1024
              },
              "user" : {
                "properties" : {
                  "email" : {
                    "type" : "keyword",
                    "ignore_above" : 1024
                  },
                  "full_name" : {
                    "type" : "keyword",
                    "ignore_above" : 1024
                  },
                  "hash" : {
                    "type" : "keyword",
                    "ignore_above" : 1024
                  },
                  "id" : {
                    "type" : "keyword",
                    "ignore_above" : 1024
                  },
                  "name" : {
                    "type" : "keyword",
                    "ignore_above" : 1024
                  }
                }
              }
            }
          },
          "tags" : {
            "type" : "keyword",
            "ignore_above" : 1024
          }
        }
      }
    }
  }
}
```

**Comment by untergeek** [comment] 2020-04-02 23:15
There's what we're missing for 6.x: 
```
"mappings" : {
      "_doc" : {
```
Document type is still required, but should be pinned as `_doc` in 6.8

To correct the patch template for 6.8, use this (note the addition of the mapping type line with `_doc`):
```
PUT _template/hass-index-template-v4_1
{
  "order": 2,
  "index_patterns": [
    "hass-events-v4*"
  ],
  "settings": {
    "index": {
      "codec": "best_compression",
      "mapping": {
        "total_fields": {
          "limit": "1000"
        }
      }
    }
  },
  "mappings": {
    "_doc": {
      "dynamic": "strict",
      "dynamic_templates": [
        {
          "hass_attributes": {
            "path_match": "hass.attributes.*",
            "mapping": {
              "type": "text",
              "fields": {
                "keyword": {
                  "ignore_above": 128,
                  "type": "keyword"
                },
                "float": {
                  "ignore_malformed": true,
                  "type": "float"
                }
              }
            }
          }
        }
      ]
    }
  }
}
```

So, do the same procedure as last time, but with this v4_1 of the patch template. I think it should work. You should try to add it **WITHOUT** `?include_type_name=false` first, as we apparently need the type name to be `_doc` for 6.8.

**Comment by kkellner** [comment] 2020-04-04 08:38
Well I ended up updating to v7.6.2 and following your original instructions with v4_1.   It seems to be working for the original case I provided.   However, I'm getting a new one:

`Error publishing documents to Elasticsearch: ('1 document(s) failed to index.', [{'index': {'_index': 'hass-events-v4-000001', '_type': '_doc', '_id': 'UaJDRHEBdrLqniB6CMSF', 'status': 400, 'error': {'type': 'mapper_parsing_exception', 'reason': "failed to parse field [hass.attributes.forecast] of type [text] in document with id 'UaJDRHEBdrLqniB6CMSF'. Preview of field's value: '{templow=33, precipitation=null, datetime=2020-04-04T06:00:00+00:00, condition=partlycloudy, wind_bearing=155, temperature=59, wind_speed=4.68}'", 'caused_by': {'type': 'illegal_state_exception', 'reason': "Can't get text on a START_OBJECT at 1:348"}}, 'data': {'hass.domain': 'weather', 'hass.object_id': 'dark_sky', 'hass.object_id_lower': 'dark_sky', 'hass.entity_id': 'weather.dark_sky', 'hass.entity_id_lower': 'weather.dark_sky', 'hass.attributes': {'temperature': 31, 'humidity': 62, 'ozone': 364.6, 'pressure': 30.03, 'wind_bearing': 211, 'wind_speed': 5.45, 'visibility': 10, 'attribution': 'Powered by Dark Sky', 'forecast': [{'datetime': '2020-04-04T06:00:00+00:00', 'temperature': 59, 'templow': 33, 'precipitation': None, 'wind_speed': 4.68, 'wind_bearing': 155, 'condition': 'partlycloudy'}, {'datetime': '2020-04-05T06:00:00+00:00', 'temperature': 70, 'templow': 37, 'precipitation': None, 'wind_speed': 6.39, 'wind_bearing': 221, 'condition': 'partlycloudy'}, {'datetime': '2020-04-06T06:00:00+00:00', 'temperature': 68, 'templow': 38, 'precipitation': None, 'wind_speed': 7.37, 'wind_bearing': 220, 'condition': 'sunny'}, {'datetime': '2020-04-07T06:00:00+00:00', 'temperature': 73, 'templow': 35, 'precipitation': None, 'wind_speed': 6.27, 'wind_bearing': 239, 'condition': 'sunny'}, {'datetime': '2020-04-08T06:00:00+00:00', 'temperature': 56, 'templow': 30, 'precipitation': 0.1, 'wind_speed': 5.37, 'wind_bearing': 348, 'condition': 'fog'}, {'datetime': '2020-04-09T06:00:00+00:00', 'temperature': 55, 'templow': 29, 'precipitation': None, 'wind_speed': 4.31, 'wind_bearing': 69, 'condition': 'partlycloudy'}, {'datetime': '2020-04-10T06:00:00+00:00', 'temperature': 65, 'templow': 36, 'precipitation': None, 'wind_speed': 4.49, 'wind_bearing': 117, 'condition': 'sunny'}, {'datetime': '2020-04-11T06:00:00+00:00', 'temperature': 72, 'templow': 33, 'precipitation': None, 'wind_speed': 5.26, 'wind_bearing': 230, 'condition': 'sunny'}], 'friendly_name': 'Dark Sky'}, 'hass.value': 'clear-night', '@timestamp': datetime.datetime(2020, 4, 4, 8, 16, 14, 349987, tzinfo=<UTC>), 'agent.name': 'My Home Assistant', 'agent.type': 'hass', 'agent.version': '0.107.7', 'ecs.version': '1.0.0', 'host.geo.location': {'lat': 999, 'lon': -999}, 'host.architecture': 'x86_64', 'host.os.name': 'Linux', 'host.hostname': 'homeassistant', 'tags': ['hass']}}}])
`

**Comment by untergeek** [comment] 2020-04-04 15:12
It appears that some values from Dark Sky are invalid JSON. You’ll have to exclude the weather.dark_sky entity (Home Assistant also discontinued support for Dark Sky anyway, since Apple acquired them this week and announced API access would go away).

**Comment by legrego** [comment] 2020-04-06 17:25
> It appears that some values from Dark Sky are invalid JSON. You’ll have to exclude the weather.dark_sky entity (Home Assistant also discontinued support for Dark Sky anyway, since Apple acquired them this week and announced API access would go away). 

I had a similar error happen with the HACS component when testing this locally. I wonder if it’s throwing an error any time an attribute’s value is a JSON object, as opposed to a string of text. I’ll take a closer look at my error to see if that’s the case...if so, we could remediate this by storing the stringified json value, or dropping that attribute altogether

**Comment by untergeek** [comment] 2020-04-17 19:59
>I wonder if it’s throwing an error any time an attribute’s value is a JSON object, as opposed to a string of text.

Oh, this is definitely it. Since the mappings are already set, when you try to send an object to a `text` or `keyword`, it will reject like this. Force-escaping JSON into strings would fix it.

**Comment by legrego** [comment] 2020-04-26 14:13
> > I wonder if it’s throwing an error any time an attribute’s value is a JSON object, as opposed to a string of text.
> 
> Oh, this is definitely it. Since the mappings are already set, when you try to send an object to a `text` or `keyword`, it will reject like this. Force-escaping JSON into strings would fix it.

This unfortunately is the case with lists as well. If anyone is relying in an attribute's value being a string array, for example, then we would have to escape this as well, which might break some queries.

For example, `group`s have an `attributes.entity_id` property, which is an array of all entity ids which belong to that group. We have to escape those now because a string array can't be index into a `text` field (at least from what I can tell)

**Comment by legrego** [comment] 2020-04-27 11:32
Beta version is available [here](https://github.com/legrego/homeassistant-elasticsearch/releases/tag/v0.2.2-beta.1) which should resolve this. I'll release as the next patch version if all goes well.

**Closed** 2020-05-01 11:13 UTC
Labels: bug
