### ISSUE TITLE
only_publish_changed: true - not working?

### ISSUE THREAD

**Issue by MrBoggi** [legrego/homeassistant-elasticsearch#28] opened 2018-09-02 17:15 UTC
To reduce amout of data stored I would like to store only when value changes. For this I can use the option only_publish_changed: true

This is turned on but it seems like it is logging same value serveral times:
![image](https://user-images.githubusercontent.com/25028288/44958707-42b90b80-aee4-11e8-94d3-dc4ba56b9ec7.png)

As you can see, both documents has the same value and the entity is sorted by time.
I was not expecting to see two entries with value 17

Yes, Home Assistant has been restarted after adding the config variable to the configuration. My config is as follows:

`elastic:
    # URL should point to your Elasticsearch cluster
    url: !secret elkserver
    only_publish_changed: true`

**Comment by legrego** [comment] 2018-09-02 18:11
`only_publish_changed` is meant to effectively disable the feature I introduced with #22, and I believe it's doing that. I think perhaps the configuration name and description could be updated to be more accurate.

To solve what you are experiencing, I wonder if we could attempt to detect this by comparing the `state.last_updated` time to the last time this plugin published events to Elasticsearch. I can experiment with this and see if it helps.

I would also like to add the ability to filter specific domains or entities from being published at all. For example, I don't ever need `groups` or `automations` to be published, so it would be nice to exclude those. Additionally, there are specific `switch` entities that I don't need published, but most others I do.

**Comment by MrBoggi** [comment] 2018-09-02 18:48
@legrego The features you mention and want to implement, I really think is good features to this "plugin".

**Comment by legrego** [comment] 2018-09-02 19:57
@MrBoggi I had some free time today, so I implemented #29 to allow specific domains and entities to be excluded from publishing to Elasticsearch.

This does not solve the original issue here, but this should allow you to reduce the amount of data you are sending if you have entities you don't care about.

Are you ok closing this issue, since the configuration option is working as intended? We can always open a new issue to enhance state tracking if needed.

**Comment by legrego** [comment] 2018-09-07 13:47
Closing - feel free to reopen if needed!

**Closed by legrego** 2018-09-07 13:47 UTC

**Comment by sejnub** [comment] 2019-01-08 20:33
Hi!

I am sorry but I don't get it. I can see absolutely now difference between the behaviours with:
`only_publish_changed: true`
and
`only_publish_changed: false`

In both cases each entity is published at the interval specified with 
`publish_frequency: 5`

My config is:
```
elastic:
  # URL should point to your Elasticsearch cluster
  url: http://elasticsearch.internal:9200
  publish_frequency: 5
  only_publish_changed: true
  exclude:
    domains: ['group']
```
Could you help? Maybe I just don't understand the documentation.
